export interface SaveFileInput {
  projectId: string;
  extension: string;

  // Exactly one of these two must be provided.
  //
  // buffer — the original path (image/provider-generated bytes already
  // held in memory).
  //
  // sourcePath — a file already written to disk (e.g. by a streaming
  // multer upload) that should be moved into the storage root without
  // ever being read into a Buffer. Added for Sprint 7.2.1 video uploads,
  // where buffering a multi-hundred-MB file in Node memory risks tripping
  // PM2's max_memory_restart ceiling (ecosystem.config.cjs) — see
  // VideoSourceService.
  buffer?: Buffer;
  sourcePath?: string;
}

export interface SavedFile {
  path: string;
  url: string;
  bytes: number;
}

export interface StorageProvider {
  save(input: SaveFileInput): Promise<SavedFile>;

  delete(path: string): Promise<void>;

  getUrl(path: string): string;

  // Resolves a stored, relative path back to a real filesystem path — added
  // for Sprint 7.2.3's VideoExecutionEngineService, which needs to hand a
  // source video's actual file to FFmpeg (a local CLI tool, not an HTTP
  // client that could use getUrl()).
  getAbsolutePath(path: string): string;
}
