/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedSettingsRouteRouteImport } from './routes/app/_authenticated/settings/route'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as AppAuthenticatedAiChatIndexRouteImport } from './routes/app/_authenticated/ai-chat/index'
import { Route as AppAuthenticatedContentStudioIndexRouteImport } from './routes/app/_authenticated/content-studio/index'
import { Route as AppAuthenticatedContentStudioProjectIdRouteImport } from './routes/app/_authenticated/content-studio/$projectId'
import { Route as AppAuthenticatedContentStudioDashboardRouteImport } from './routes/app/_authenticated/content-studio/dashboard'
import { Route as AppAuthenticatedContentStudioPromptLibraryRouteImport } from './routes/app/_authenticated/content-studio/prompt-library'
import { Route as AppAuthenticatedErrorsErrorRouteImport } from './routes/app/_authenticated/errors/$error'
import { Route as AppAuthenticatedFinanceIndexRouteImport } from './routes/app/_authenticated/finance/index'
import { Route as AppAuthenticatedModelsIndexRouteImport } from './routes/app/_authenticated/models/index'
import { Route as AppAuthenticatedRolesIndexRouteImport } from './routes/app/_authenticated/roles/index'
import { Route as AppAuthenticatedSettingsIndexRouteImport } from './routes/app/_authenticated/settings/index'
import { Route as AppAuthenticatedSettingsAccountRouteImport } from './routes/app/_authenticated/settings/account'
import { Route as AppAuthenticatedSettingsAppearanceRouteImport } from './routes/app/_authenticated/settings/appearance'
import { Route as AppAuthenticatedSettingsDisplayRouteImport } from './routes/app/_authenticated/settings/display'
import { Route as AppAuthenticatedSettingsNotificationsRouteImport } from './routes/app/_authenticated/settings/notifications'
import { Route as AppAuthenticatedSettingsProvidersRouteImport } from './routes/app/_authenticated/settings/providers'
import { Route as AppAuthenticatedUsersIndexRouteImport } from './routes/app/_authenticated/users/index'
import { Route as AppAuthenticatedAutomationAuditLogsIndexRouteImport } from './routes/app/_authenticated/automation/audit-logs/index'
import { Route as AppAuthenticatedAutomationConnectionsIndexRouteImport } from './routes/app/_authenticated/automation/connections/index'
import { Route as AppAuthenticatedAutomationHealthIndexRouteImport } from './routes/app/_authenticated/automation/health/index'
import { Route as AppAuthenticatedAutomationMcpServersIndexRouteImport } from './routes/app/_authenticated/automation/mcp-servers/index'
import { Route as AppAuthenticatedAutomationProvidersIndexRouteImport } from './routes/app/_authenticated/automation/providers/index'
import { Route as AppAuthenticatedFinanceExpensesIndexRouteImport } from './routes/app/_authenticated/finance/expenses/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedSettingsRouteRoute =
  AppAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AppAuthenticatedAiChatIndexRoute =
  AppAuthenticatedAiChatIndexRouteImport.update({
    id: '/ai-chat/',
    path: '/ai-chat/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioIndexRoute =
  AppAuthenticatedContentStudioIndexRouteImport.update({
    id: '/content-studio/',
    path: '/content-studio/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioProjectIdRoute =
  AppAuthenticatedContentStudioProjectIdRouteImport.update({
    id: '/content-studio/$projectId',
    path: '/content-studio/$projectId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioDashboardRoute =
  AppAuthenticatedContentStudioDashboardRouteImport.update({
    id: '/content-studio/dashboard',
    path: '/content-studio/dashboard',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioPromptLibraryRoute =
  AppAuthenticatedContentStudioPromptLibraryRouteImport.update({
    id: '/content-studio/prompt-library',
    path: '/content-studio/prompt-library',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedErrorsErrorRoute =
  AppAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedFinanceIndexRoute =
  AppAuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedModelsIndexRoute =
  AppAuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRolesIndexRoute =
  AppAuthenticatedRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedSettingsIndexRoute =
  AppAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAccountRoute =
  AppAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAppearanceRoute =
  AppAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsDisplayRoute =
  AppAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsNotificationsRoute =
  AppAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsProvidersRoute =
  AppAuthenticatedSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedUsersIndexRoute =
  AppAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationAuditLogsIndexRoute =
  AppAuthenticatedAutomationAuditLogsIndexRouteImport.update({
    id: '/automation/audit-logs/',
    path: '/automation/audit-logs/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationConnectionsIndexRoute =
  AppAuthenticatedAutomationConnectionsIndexRouteImport.update({
    id: '/automation/connections/',
    path: '/automation/connections/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationHealthIndexRoute =
  AppAuthenticatedAutomationHealthIndexRouteImport.update({
    id: '/automation/health/',
    path: '/automation/health/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationMcpServersIndexRoute =
  AppAuthenticatedAutomationMcpServersIndexRouteImport.update({
    id: '/automation/mcp-servers/',
    path: '/automation/mcp-servers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationProvidersIndexRoute =
  AppAuthenticatedAutomationProvidersIndexRouteImport.update({
    id: '/automation/providers/',
    path: '/automation/providers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedFinanceExpensesIndexRoute =
  AppAuthenticatedFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/app/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/ai-chat/': typeof AppAuthenticatedAiChatIndexRoute
  '/app/content-studio/': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/finance/': typeof AppAuthenticatedFinanceIndexRoute
  '/app/models/': typeof AppAuthenticatedModelsIndexRoute
  '/app/roles/': typeof AppAuthenticatedRolesIndexRoute
  '/app/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/automation/audit-logs/': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/automation/connections/': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/automation/health/': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/automation/mcp-servers/': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/automation/providers/': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/finance/expenses/': typeof AppAuthenticatedFinanceExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/ai-chat': typeof AppAuthenticatedAiChatIndexRoute
  '/app/content-studio': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/finance': typeof AppAuthenticatedFinanceIndexRoute
  '/app/models': typeof AppAuthenticatedModelsIndexRoute
  '/app/roles': typeof AppAuthenticatedRolesIndexRoute
  '/app/settings': typeof AppAuthenticatedSettingsIndexRoute
  '/app/users': typeof AppAuthenticatedUsersIndexRoute
  '/app/automation/audit-logs': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/automation/connections': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/automation/health': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/automation/mcp-servers': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/automation/providers': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/finance/expenses': typeof AppAuthenticatedFinanceExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/app/_authenticated/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/_authenticated/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/_authenticated/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/_authenticated/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/_authenticated/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/_authenticated/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/_authenticated/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/_authenticated/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/_authenticated/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/_authenticated/ai-chat/': typeof AppAuthenticatedAiChatIndexRoute
  '/app/_authenticated/content-studio/': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/_authenticated/finance/': typeof AppAuthenticatedFinanceIndexRoute
  '/app/_authenticated/models/': typeof AppAuthenticatedModelsIndexRoute
  '/app/_authenticated/roles/': typeof AppAuthenticatedRolesIndexRoute
  '/app/_authenticated/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/_authenticated/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/_authenticated/automation/audit-logs/': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/_authenticated/automation/connections/': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/_authenticated/automation/health/': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/_authenticated/automation/mcp-servers/': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/_authenticated/automation/providers/': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/_authenticated/finance/expenses/': typeof AppAuthenticatedFinanceExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/app'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/app/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/app/'
    | '/app/content-studio/$projectId'
    | '/app/content-studio/dashboard'
    | '/app/content-studio/prompt-library'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/notifications'
    | '/app/settings/providers'
    | '/app/ai-chat/'
    | '/app/content-studio/'
    | '/app/finance/'
    | '/app/models/'
    | '/app/roles/'
    | '/app/settings/'
    | '/app/users/'
    | '/app/automation/audit-logs/'
    | '/app/automation/connections/'
    | '/app/automation/health/'
    | '/app/automation/mcp-servers/'
    | '/app/automation/providers/'
    | '/app/finance/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/app'
    | '/app/content-studio/$projectId'
    | '/app/content-studio/dashboard'
    | '/app/content-studio/prompt-library'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/notifications'
    | '/app/settings/providers'
    | '/app/ai-chat'
    | '/app/content-studio'
    | '/app/finance'
    | '/app/models'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/automation/audit-logs'
    | '/app/automation/connections'
    | '/app/automation/health'
    | '/app/automation/mcp-servers'
    | '/app/automation/providers'
    | '/app/finance/expenses'
  id:
    | '__root__'
    | '/'
    | '/clerk'
    | '/app/_authenticated'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/app/_authenticated/settings'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/app/_authenticated/'
    | '/app/_authenticated/content-studio/$projectId'
    | '/app/_authenticated/content-studio/dashboard'
    | '/app/_authenticated/content-studio/prompt-library'
    | '/app/_authenticated/errors/$error'
    | '/app/_authenticated/settings/account'
    | '/app/_authenticated/settings/appearance'
    | '/app/_authenticated/settings/display'
    | '/app/_authenticated/settings/notifications'
    | '/app/_authenticated/settings/providers'
    | '/app/_authenticated/ai-chat/'
    | '/app/_authenticated/content-studio/'
    | '/app/_authenticated/finance/'
    | '/app/_authenticated/models/'
    | '/app/_authenticated/roles/'
    | '/app/_authenticated/settings/'
    | '/app/_authenticated/users/'
    | '/app/_authenticated/automation/audit-logs/'
    | '/app/_authenticated/automation/connections/'
    | '/app/_authenticated/automation/health/'
    | '/app/_authenticated/automation/mcp-servers/'
    | '/app/_authenticated/automation/providers/'
    | '/app/_authenticated/finance/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings': {
      id: '/app/_authenticated/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/app/_authenticated/ai-chat/': {
      id: '/app/_authenticated/ai-chat/'
      path: '/ai-chat'
      fullPath: '/app/ai-chat/'
      preLoaderRoute: typeof AppAuthenticatedAiChatIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/': {
      id: '/app/_authenticated/content-studio/'
      path: '/content-studio'
      fullPath: '/app/content-studio/'
      preLoaderRoute: typeof AppAuthenticatedContentStudioIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/$projectId': {
      id: '/app/_authenticated/content-studio/$projectId'
      path: '/content-studio/$projectId'
      fullPath: '/app/content-studio/$projectId'
      preLoaderRoute: typeof AppAuthenticatedContentStudioProjectIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/dashboard': {
      id: '/app/_authenticated/content-studio/dashboard'
      path: '/content-studio/dashboard'
      fullPath: '/app/content-studio/dashboard'
      preLoaderRoute: typeof AppAuthenticatedContentStudioDashboardRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/prompt-library': {
      id: '/app/_authenticated/content-studio/prompt-library'
      path: '/content-studio/prompt-library'
      fullPath: '/app/content-studio/prompt-library'
      preLoaderRoute: typeof AppAuthenticatedContentStudioPromptLibraryRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/errors/$error': {
      id: '/app/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/app/errors/$error'
      preLoaderRoute: typeof AppAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/finance/': {
      id: '/app/_authenticated/finance/'
      path: '/finance'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppAuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/models/': {
      id: '/app/_authenticated/models/'
      path: '/models'
      fullPath: '/app/models/'
      preLoaderRoute: typeof AppAuthenticatedModelsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/roles/': {
      id: '/app/_authenticated/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppAuthenticatedRolesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings/': {
      id: '/app/_authenticated/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/account': {
      id: '/app/_authenticated/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/appearance': {
      id: '/app/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/display': {
      id: '/app/_authenticated/settings/display'
      path: '/display'
      fullPath: '/app/settings/display'
      preLoaderRoute: typeof AppAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/notifications': {
      id: '/app/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/providers': {
      id: '/app/_authenticated/settings/providers'
      path: '/providers'
      fullPath: '/app/settings/providers'
      preLoaderRoute: typeof AppAuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/users/': {
      id: '/app/_authenticated/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppAuthenticatedUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/audit-logs/': {
      id: '/app/_authenticated/automation/audit-logs/'
      path: '/automation/audit-logs'
      fullPath: '/app/automation/audit-logs/'
      preLoaderRoute: typeof AppAuthenticatedAutomationAuditLogsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/connections/': {
      id: '/app/_authenticated/automation/connections/'
      path: '/automation/connections'
      fullPath: '/app/automation/connections/'
      preLoaderRoute: typeof AppAuthenticatedAutomationConnectionsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/health/': {
      id: '/app/_authenticated/automation/health/'
      path: '/automation/health'
      fullPath: '/app/automation/health/'
      preLoaderRoute: typeof AppAuthenticatedAutomationHealthIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/mcp-servers/': {
      id: '/app/_authenticated/automation/mcp-servers/'
      path: '/automation/mcp-servers'
      fullPath: '/app/automation/mcp-servers/'
      preLoaderRoute: typeof AppAuthenticatedAutomationMcpServersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/providers/': {
      id: '/app/_authenticated/automation/providers/'
      path: '/automation/providers'
      fullPath: '/app/automation/providers/'
      preLoaderRoute: typeof AppAuthenticatedAutomationProvidersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/finance/expenses/': {
      id: '/app/_authenticated/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/app/finance/expenses/'
      preLoaderRoute: typeof AppAuthenticatedFinanceExpensesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRoute
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRoute,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface AppAuthenticatedSettingsRouteRouteChildren {
  AppAuthenticatedSettingsAccountRoute: typeof AppAuthenticatedSettingsAccountRoute
  AppAuthenticatedSettingsAppearanceRoute: typeof AppAuthenticatedSettingsAppearanceRoute
  AppAuthenticatedSettingsDisplayRoute: typeof AppAuthenticatedSettingsDisplayRoute
  AppAuthenticatedSettingsNotificationsRoute: typeof AppAuthenticatedSettingsNotificationsRoute
  AppAuthenticatedSettingsProvidersRoute: typeof AppAuthenticatedSettingsProvidersRoute
  AppAuthenticatedSettingsIndexRoute: typeof AppAuthenticatedSettingsIndexRoute
}

const AppAuthenticatedSettingsRouteRouteChildren: AppAuthenticatedSettingsRouteRouteChildren =
  {
    AppAuthenticatedSettingsAccountRoute: AppAuthenticatedSettingsAccountRoute,
    AppAuthenticatedSettingsAppearanceRoute:
      AppAuthenticatedSettingsAppearanceRoute,
    AppAuthenticatedSettingsDisplayRoute: AppAuthenticatedSettingsDisplayRoute,
    AppAuthenticatedSettingsNotificationsRoute:
      AppAuthenticatedSettingsNotificationsRoute,
    AppAuthenticatedSettingsProvidersRoute:
      AppAuthenticatedSettingsProvidersRoute,
    AppAuthenticatedSettingsIndexRoute: AppAuthenticatedSettingsIndexRoute,
  }

const AppAuthenticatedSettingsRouteRouteWithChildren =
  AppAuthenticatedSettingsRouteRoute._addFileChildren(
    AppAuthenticatedSettingsRouteRouteChildren,
  )

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedSettingsRouteRoute: typeof AppAuthenticatedSettingsRouteRouteWithChildren
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedContentStudioProjectIdRoute: typeof AppAuthenticatedContentStudioProjectIdRoute
  AppAuthenticatedContentStudioDashboardRoute: typeof AppAuthenticatedContentStudioDashboardRoute
  AppAuthenticatedContentStudioPromptLibraryRoute: typeof AppAuthenticatedContentStudioPromptLibraryRoute
  AppAuthenticatedErrorsErrorRoute: typeof AppAuthenticatedErrorsErrorRoute
  AppAuthenticatedAiChatIndexRoute: typeof AppAuthenticatedAiChatIndexRoute
  AppAuthenticatedContentStudioIndexRoute: typeof AppAuthenticatedContentStudioIndexRoute
  AppAuthenticatedFinanceIndexRoute: typeof AppAuthenticatedFinanceIndexRoute
  AppAuthenticatedModelsIndexRoute: typeof AppAuthenticatedModelsIndexRoute
  AppAuthenticatedRolesIndexRoute: typeof AppAuthenticatedRolesIndexRoute
  AppAuthenticatedUsersIndexRoute: typeof AppAuthenticatedUsersIndexRoute
  AppAuthenticatedAutomationAuditLogsIndexRoute: typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  AppAuthenticatedAutomationConnectionsIndexRoute: typeof AppAuthenticatedAutomationConnectionsIndexRoute
  AppAuthenticatedAutomationHealthIndexRoute: typeof AppAuthenticatedAutomationHealthIndexRoute
  AppAuthenticatedAutomationMcpServersIndexRoute: typeof AppAuthenticatedAutomationMcpServersIndexRoute
  AppAuthenticatedAutomationProvidersIndexRoute: typeof AppAuthenticatedAutomationProvidersIndexRoute
  AppAuthenticatedFinanceExpensesIndexRoute: typeof AppAuthenticatedFinanceExpensesIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedSettingsRouteRoute:
    AppAuthenticatedSettingsRouteRouteWithChildren,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedContentStudioProjectIdRoute:
    AppAuthenticatedContentStudioProjectIdRoute,
  AppAuthenticatedContentStudioDashboardRoute:
    AppAuthenticatedContentStudioDashboardRoute,
  AppAuthenticatedContentStudioPromptLibraryRoute:
    AppAuthenticatedContentStudioPromptLibraryRoute,
  AppAuthenticatedErrorsErrorRoute: AppAuthenticatedErrorsErrorRoute,
  AppAuthenticatedAiChatIndexRoute: AppAuthenticatedAiChatIndexRoute,
  AppAuthenticatedContentStudioIndexRoute:
    AppAuthenticatedContentStudioIndexRoute,
  AppAuthenticatedFinanceIndexRoute: AppAuthenticatedFinanceIndexRoute,
  AppAuthenticatedModelsIndexRoute: AppAuthenticatedModelsIndexRoute,
  AppAuthenticatedRolesIndexRoute: AppAuthenticatedRolesIndexRoute,
  AppAuthenticatedUsersIndexRoute: AppAuthenticatedUsersIndexRoute,
  AppAuthenticatedAutomationAuditLogsIndexRoute:
    AppAuthenticatedAutomationAuditLogsIndexRoute,
  AppAuthenticatedAutomationConnectionsIndexRoute:
    AppAuthenticatedAutomationConnectionsIndexRoute,
  AppAuthenticatedAutomationHealthIndexRoute:
    AppAuthenticatedAutomationHealthIndexRoute,
  AppAuthenticatedAutomationMcpServersIndexRoute:
    AppAuthenticatedAutomationMcpServersIndexRoute,
  AppAuthenticatedAutomationProvidersIndexRoute:
    AppAuthenticatedAutomationProvidersIndexRoute,
  AppAuthenticatedFinanceExpensesIndexRoute:
    AppAuthenticatedFinanceExpensesIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
