/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/app/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedSettingsRouteRouteImport } from './routes/app/_authenticated/settings/route'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as AppAuthenticatedAiChatIndexRouteImport } from './routes/app/_authenticated/ai-chat/index'
import { Route as AppAuthenticatedAiCoreIndexRouteImport } from './routes/app/_authenticated/ai-core/index'
import { Route as AppAuthenticatedContentStudioIndexRouteImport } from './routes/app/_authenticated/content-studio/index'
import { Route as AppAuthenticatedContentStudioProjectIdRouteImport } from './routes/app/_authenticated/content-studio/$projectId'
import { Route as AppAuthenticatedContentStudioDashboardRouteImport } from './routes/app/_authenticated/content-studio/dashboard'
import { Route as AppAuthenticatedContentStudioPromptLibraryRouteImport } from './routes/app/_authenticated/content-studio/prompt-library'
import { Route as AppAuthenticatedCrmIndexRouteImport } from './routes/app/_authenticated/crm/index'
import { Route as AppAuthenticatedErrorsErrorRouteImport } from './routes/app/_authenticated/errors/$error'
import { Route as AppAuthenticatedFinanceIndexRouteImport } from './routes/app/_authenticated/finance/index'
import { Route as AppAuthenticatedModelsIndexRouteImport } from './routes/app/_authenticated/models/index'
import { Route as AppAuthenticatedPresentationEngineIndexRouteImport } from './routes/app/_authenticated/presentation-engine/index'
import { Route as AppAuthenticatedRestaurantIndexRouteImport } from './routes/app/_authenticated/restaurant/index'
import { Route as AppAuthenticatedRolesIndexRouteImport } from './routes/app/_authenticated/roles/index'
import { Route as AppAuthenticatedSettingsIndexRouteImport } from './routes/app/_authenticated/settings/index'
import { Route as AppAuthenticatedSettingsAccountRouteImport } from './routes/app/_authenticated/settings/account'
import { Route as AppAuthenticatedSettingsAppearanceRouteImport } from './routes/app/_authenticated/settings/appearance'
import { Route as AppAuthenticatedSettingsDisplayRouteImport } from './routes/app/_authenticated/settings/display'
import { Route as AppAuthenticatedSettingsNotificationsRouteImport } from './routes/app/_authenticated/settings/notifications'
import { Route as AppAuthenticatedSettingsProvidersRouteImport } from './routes/app/_authenticated/settings/providers'
import { Route as AppAuthenticatedUsersIndexRouteImport } from './routes/app/_authenticated/users/index'
import { Route as AppAuthenticatedAiCoreAuditIndexRouteImport } from './routes/app/_authenticated/ai-core/audit/index'
import { Route as AppAuthenticatedAiCoreBrainsIndexRouteImport } from './routes/app/_authenticated/ai-core/brains/index'
import { Route as AppAuthenticatedAiCoreBrainsBrainIdRouteImport } from './routes/app/_authenticated/ai-core/brains/$brainId'
import { Route as AppAuthenticatedAiCoreCapabilitiesIndexRouteImport } from './routes/app/_authenticated/ai-core/capabilities/index'
import { Route as AppAuthenticatedAiCoreCostsIndexRouteImport } from './routes/app/_authenticated/ai-core/costs/index'
import { Route as AppAuthenticatedAiCoreHealthIndexRouteImport } from './routes/app/_authenticated/ai-core/health/index'
import { Route as AppAuthenticatedAiCoreModelsIndexRouteImport } from './routes/app/_authenticated/ai-core/models/index'
import { Route as AppAuthenticatedAiCorePlaygroundIndexRouteImport } from './routes/app/_authenticated/ai-core/playground/index'
import { Route as AppAuthenticatedAiCoreProvidersIndexRouteImport } from './routes/app/_authenticated/ai-core/providers/index'
import { Route as AppAuthenticatedAiCoreUsageIndexRouteImport } from './routes/app/_authenticated/ai-core/usage/index'
import { Route as AppAuthenticatedAutomationAuditLogsIndexRouteImport } from './routes/app/_authenticated/automation/audit-logs/index'
import { Route as AppAuthenticatedAutomationConnectionsIndexRouteImport } from './routes/app/_authenticated/automation/connections/index'
import { Route as AppAuthenticatedAutomationHealthIndexRouteImport } from './routes/app/_authenticated/automation/health/index'
import { Route as AppAuthenticatedAutomationMcpServersIndexRouteImport } from './routes/app/_authenticated/automation/mcp-servers/index'
import { Route as AppAuthenticatedAutomationProvidersIndexRouteImport } from './routes/app/_authenticated/automation/providers/index'
import { Route as AppAuthenticatedCrmLeadsIndexRouteImport } from './routes/app/_authenticated/crm/leads/index'
import { Route as AppAuthenticatedCrmLeadsLeadIdRouteImport } from './routes/app/_authenticated/crm/leads/$leadId'
import { Route as AppAuthenticatedFinanceExpensesIndexRouteImport } from './routes/app/_authenticated/finance/expenses/index'
import { Route as AppAuthenticatedRestaurantBranchesIndexRouteImport } from './routes/app/_authenticated/restaurant/branches/index'
import { Route as AppAuthenticatedRestaurantIngredientCategoriesIndexRouteImport } from './routes/app/_authenticated/restaurant/ingredient-categories/index'
import { Route as AppAuthenticatedRestaurantIngredientsIndexRouteImport } from './routes/app/_authenticated/restaurant/ingredients/index'
import { Route as AppAuthenticatedRestaurantMenuCategoriesIndexRouteImport } from './routes/app/_authenticated/restaurant/menu-categories/index'
import { Route as AppAuthenticatedRestaurantMenuItemsIndexRouteImport } from './routes/app/_authenticated/restaurant/menu-items/index'
import { Route as AppAuthenticatedRestaurantRecipesIndexRouteImport } from './routes/app/_authenticated/restaurant/recipes/index'
import { Route as AppAuthenticatedRestaurantRestaurantsIndexRouteImport } from './routes/app/_authenticated/restaurant/restaurants/index'
import { Route as AppAuthenticatedRestaurantStaffIndexRouteImport } from './routes/app/_authenticated/restaurant/staff/index'
import { Route as AppAuthenticatedRestaurantSuppliersIndexRouteImport } from './routes/app/_authenticated/restaurant/suppliers/index'
import { Route as AppAuthenticatedRestaurantUnitsIndexRouteImport } from './routes/app/_authenticated/restaurant/units/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRouteRoute,
} as any)
const AppAuthenticatedSettingsRouteRoute =
  AppAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AppAuthenticatedAiChatIndexRoute =
  AppAuthenticatedAiChatIndexRouteImport.update({
    id: '/ai-chat/',
    path: '/ai-chat/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreIndexRoute =
  AppAuthenticatedAiCoreIndexRouteImport.update({
    id: '/ai-core/',
    path: '/ai-core/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioIndexRoute =
  AppAuthenticatedContentStudioIndexRouteImport.update({
    id: '/content-studio/',
    path: '/content-studio/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioProjectIdRoute =
  AppAuthenticatedContentStudioProjectIdRouteImport.update({
    id: '/content-studio/$projectId',
    path: '/content-studio/$projectId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioDashboardRoute =
  AppAuthenticatedContentStudioDashboardRouteImport.update({
    id: '/content-studio/dashboard',
    path: '/content-studio/dashboard',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedContentStudioPromptLibraryRoute =
  AppAuthenticatedContentStudioPromptLibraryRouteImport.update({
    id: '/content-studio/prompt-library',
    path: '/content-studio/prompt-library',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCrmIndexRoute =
  AppAuthenticatedCrmIndexRouteImport.update({
    id: '/crm/',
    path: '/crm/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedErrorsErrorRoute =
  AppAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedFinanceIndexRoute =
  AppAuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedModelsIndexRoute =
  AppAuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedPresentationEngineIndexRoute =
  AppAuthenticatedPresentationEngineIndexRouteImport.update({
    id: '/presentation-engine/',
    path: '/presentation-engine/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantIndexRoute =
  AppAuthenticatedRestaurantIndexRouteImport.update({
    id: '/restaurant/',
    path: '/restaurant/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRolesIndexRoute =
  AppAuthenticatedRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedSettingsIndexRoute =
  AppAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAccountRoute =
  AppAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsAppearanceRoute =
  AppAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsDisplayRoute =
  AppAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsNotificationsRoute =
  AppAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedSettingsProvidersRoute =
  AppAuthenticatedSettingsProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AppAuthenticatedSettingsRouteRoute,
  } as any)
const AppAuthenticatedUsersIndexRoute =
  AppAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreAuditIndexRoute =
  AppAuthenticatedAiCoreAuditIndexRouteImport.update({
    id: '/ai-core/audit/',
    path: '/ai-core/audit/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreBrainsIndexRoute =
  AppAuthenticatedAiCoreBrainsIndexRouteImport.update({
    id: '/ai-core/brains/',
    path: '/ai-core/brains/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreBrainsBrainIdRoute =
  AppAuthenticatedAiCoreBrainsBrainIdRouteImport.update({
    id: '/ai-core/brains/$brainId',
    path: '/ai-core/brains/$brainId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreCapabilitiesIndexRoute =
  AppAuthenticatedAiCoreCapabilitiesIndexRouteImport.update({
    id: '/ai-core/capabilities/',
    path: '/ai-core/capabilities/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreCostsIndexRoute =
  AppAuthenticatedAiCoreCostsIndexRouteImport.update({
    id: '/ai-core/costs/',
    path: '/ai-core/costs/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreHealthIndexRoute =
  AppAuthenticatedAiCoreHealthIndexRouteImport.update({
    id: '/ai-core/health/',
    path: '/ai-core/health/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreModelsIndexRoute =
  AppAuthenticatedAiCoreModelsIndexRouteImport.update({
    id: '/ai-core/models/',
    path: '/ai-core/models/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCorePlaygroundIndexRoute =
  AppAuthenticatedAiCorePlaygroundIndexRouteImport.update({
    id: '/ai-core/playground/',
    path: '/ai-core/playground/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreProvidersIndexRoute =
  AppAuthenticatedAiCoreProvidersIndexRouteImport.update({
    id: '/ai-core/providers/',
    path: '/ai-core/providers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAiCoreUsageIndexRoute =
  AppAuthenticatedAiCoreUsageIndexRouteImport.update({
    id: '/ai-core/usage/',
    path: '/ai-core/usage/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationAuditLogsIndexRoute =
  AppAuthenticatedAutomationAuditLogsIndexRouteImport.update({
    id: '/automation/audit-logs/',
    path: '/automation/audit-logs/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationConnectionsIndexRoute =
  AppAuthenticatedAutomationConnectionsIndexRouteImport.update({
    id: '/automation/connections/',
    path: '/automation/connections/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationHealthIndexRoute =
  AppAuthenticatedAutomationHealthIndexRouteImport.update({
    id: '/automation/health/',
    path: '/automation/health/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationMcpServersIndexRoute =
  AppAuthenticatedAutomationMcpServersIndexRouteImport.update({
    id: '/automation/mcp-servers/',
    path: '/automation/mcp-servers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedAutomationProvidersIndexRoute =
  AppAuthenticatedAutomationProvidersIndexRouteImport.update({
    id: '/automation/providers/',
    path: '/automation/providers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCrmLeadsIndexRoute =
  AppAuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/crm/leads/',
    path: '/crm/leads/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedCrmLeadsLeadIdRoute =
  AppAuthenticatedCrmLeadsLeadIdRouteImport.update({
    id: '/crm/leads/$leadId',
    path: '/crm/leads/$leadId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedFinanceExpensesIndexRoute =
  AppAuthenticatedFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantBranchesIndexRoute =
  AppAuthenticatedRestaurantBranchesIndexRouteImport.update({
    id: '/restaurant/branches/',
    path: '/restaurant/branches/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantIngredientCategoriesIndexRoute =
  AppAuthenticatedRestaurantIngredientCategoriesIndexRouteImport.update({
    id: '/restaurant/ingredient-categories/',
    path: '/restaurant/ingredient-categories/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantIngredientsIndexRoute =
  AppAuthenticatedRestaurantIngredientsIndexRouteImport.update({
    id: '/restaurant/ingredients/',
    path: '/restaurant/ingredients/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantMenuCategoriesIndexRoute =
  AppAuthenticatedRestaurantMenuCategoriesIndexRouteImport.update({
    id: '/restaurant/menu-categories/',
    path: '/restaurant/menu-categories/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantMenuItemsIndexRoute =
  AppAuthenticatedRestaurantMenuItemsIndexRouteImport.update({
    id: '/restaurant/menu-items/',
    path: '/restaurant/menu-items/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantRecipesIndexRoute =
  AppAuthenticatedRestaurantRecipesIndexRouteImport.update({
    id: '/restaurant/recipes/',
    path: '/restaurant/recipes/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantRestaurantsIndexRoute =
  AppAuthenticatedRestaurantRestaurantsIndexRouteImport.update({
    id: '/restaurant/restaurants/',
    path: '/restaurant/restaurants/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantStaffIndexRoute =
  AppAuthenticatedRestaurantStaffIndexRouteImport.update({
    id: '/restaurant/staff/',
    path: '/restaurant/staff/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantSuppliersIndexRoute =
  AppAuthenticatedRestaurantSuppliersIndexRouteImport.update({
    id: '/restaurant/suppliers/',
    path: '/restaurant/suppliers/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedRestaurantUnitsIndexRoute =
  AppAuthenticatedRestaurantUnitsIndexRouteImport.update({
    id: '/restaurant/units/',
    path: '/restaurant/units/',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/app': typeof AppAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/app/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/ai-chat/': typeof AppAuthenticatedAiChatIndexRoute
  '/app/ai-core/': typeof AppAuthenticatedAiCoreIndexRoute
  '/app/content-studio/': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/crm/': typeof AppAuthenticatedCrmIndexRoute
  '/app/finance/': typeof AppAuthenticatedFinanceIndexRoute
  '/app/models/': typeof AppAuthenticatedModelsIndexRoute
  '/app/presentation-engine/': typeof AppAuthenticatedPresentationEngineIndexRoute
  '/app/restaurant/': typeof AppAuthenticatedRestaurantIndexRoute
  '/app/roles/': typeof AppAuthenticatedRolesIndexRoute
  '/app/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/ai-core/brains/$brainId': typeof AppAuthenticatedAiCoreBrainsBrainIdRoute
  '/app/crm/leads/$leadId': typeof AppAuthenticatedCrmLeadsLeadIdRoute
  '/app/ai-core/audit/': typeof AppAuthenticatedAiCoreAuditIndexRoute
  '/app/ai-core/brains/': typeof AppAuthenticatedAiCoreBrainsIndexRoute
  '/app/ai-core/capabilities/': typeof AppAuthenticatedAiCoreCapabilitiesIndexRoute
  '/app/ai-core/costs/': typeof AppAuthenticatedAiCoreCostsIndexRoute
  '/app/ai-core/health/': typeof AppAuthenticatedAiCoreHealthIndexRoute
  '/app/ai-core/models/': typeof AppAuthenticatedAiCoreModelsIndexRoute
  '/app/ai-core/playground/': typeof AppAuthenticatedAiCorePlaygroundIndexRoute
  '/app/ai-core/providers/': typeof AppAuthenticatedAiCoreProvidersIndexRoute
  '/app/ai-core/usage/': typeof AppAuthenticatedAiCoreUsageIndexRoute
  '/app/automation/audit-logs/': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/automation/connections/': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/automation/health/': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/automation/mcp-servers/': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/automation/providers/': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/crm/leads/': typeof AppAuthenticatedCrmLeadsIndexRoute
  '/app/finance/expenses/': typeof AppAuthenticatedFinanceExpensesIndexRoute
  '/app/restaurant/branches/': typeof AppAuthenticatedRestaurantBranchesIndexRoute
  '/app/restaurant/ingredient-categories/': typeof AppAuthenticatedRestaurantIngredientCategoriesIndexRoute
  '/app/restaurant/ingredients/': typeof AppAuthenticatedRestaurantIngredientsIndexRoute
  '/app/restaurant/menu-categories/': typeof AppAuthenticatedRestaurantMenuCategoriesIndexRoute
  '/app/restaurant/menu-items/': typeof AppAuthenticatedRestaurantMenuItemsIndexRoute
  '/app/restaurant/recipes/': typeof AppAuthenticatedRestaurantRecipesIndexRoute
  '/app/restaurant/restaurants/': typeof AppAuthenticatedRestaurantRestaurantsIndexRoute
  '/app/restaurant/staff/': typeof AppAuthenticatedRestaurantStaffIndexRoute
  '/app/restaurant/suppliers/': typeof AppAuthenticatedRestaurantSuppliersIndexRoute
  '/app/restaurant/units/': typeof AppAuthenticatedRestaurantUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/ai-chat': typeof AppAuthenticatedAiChatIndexRoute
  '/app/ai-core': typeof AppAuthenticatedAiCoreIndexRoute
  '/app/content-studio': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/crm': typeof AppAuthenticatedCrmIndexRoute
  '/app/finance': typeof AppAuthenticatedFinanceIndexRoute
  '/app/models': typeof AppAuthenticatedModelsIndexRoute
  '/app/presentation-engine': typeof AppAuthenticatedPresentationEngineIndexRoute
  '/app/restaurant': typeof AppAuthenticatedRestaurantIndexRoute
  '/app/roles': typeof AppAuthenticatedRolesIndexRoute
  '/app/settings': typeof AppAuthenticatedSettingsIndexRoute
  '/app/users': typeof AppAuthenticatedUsersIndexRoute
  '/app/ai-core/brains/$brainId': typeof AppAuthenticatedAiCoreBrainsBrainIdRoute
  '/app/crm/leads/$leadId': typeof AppAuthenticatedCrmLeadsLeadIdRoute
  '/app/ai-core/audit': typeof AppAuthenticatedAiCoreAuditIndexRoute
  '/app/ai-core/brains': typeof AppAuthenticatedAiCoreBrainsIndexRoute
  '/app/ai-core/capabilities': typeof AppAuthenticatedAiCoreCapabilitiesIndexRoute
  '/app/ai-core/costs': typeof AppAuthenticatedAiCoreCostsIndexRoute
  '/app/ai-core/health': typeof AppAuthenticatedAiCoreHealthIndexRoute
  '/app/ai-core/models': typeof AppAuthenticatedAiCoreModelsIndexRoute
  '/app/ai-core/playground': typeof AppAuthenticatedAiCorePlaygroundIndexRoute
  '/app/ai-core/providers': typeof AppAuthenticatedAiCoreProvidersIndexRoute
  '/app/ai-core/usage': typeof AppAuthenticatedAiCoreUsageIndexRoute
  '/app/automation/audit-logs': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/automation/connections': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/automation/health': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/automation/mcp-servers': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/automation/providers': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/crm/leads': typeof AppAuthenticatedCrmLeadsIndexRoute
  '/app/finance/expenses': typeof AppAuthenticatedFinanceExpensesIndexRoute
  '/app/restaurant/branches': typeof AppAuthenticatedRestaurantBranchesIndexRoute
  '/app/restaurant/ingredient-categories': typeof AppAuthenticatedRestaurantIngredientCategoriesIndexRoute
  '/app/restaurant/ingredients': typeof AppAuthenticatedRestaurantIngredientsIndexRoute
  '/app/restaurant/menu-categories': typeof AppAuthenticatedRestaurantMenuCategoriesIndexRoute
  '/app/restaurant/menu-items': typeof AppAuthenticatedRestaurantMenuItemsIndexRoute
  '/app/restaurant/recipes': typeof AppAuthenticatedRestaurantRecipesIndexRoute
  '/app/restaurant/restaurants': typeof AppAuthenticatedRestaurantRestaurantsIndexRoute
  '/app/restaurant/staff': typeof AppAuthenticatedRestaurantStaffIndexRoute
  '/app/restaurant/suppliers': typeof AppAuthenticatedRestaurantSuppliersIndexRoute
  '/app/restaurant/units': typeof AppAuthenticatedRestaurantUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/app/_authenticated/settings': typeof AppAuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/content-studio/$projectId': typeof AppAuthenticatedContentStudioProjectIdRoute
  '/app/_authenticated/content-studio/dashboard': typeof AppAuthenticatedContentStudioDashboardRoute
  '/app/_authenticated/content-studio/prompt-library': typeof AppAuthenticatedContentStudioPromptLibraryRoute
  '/app/_authenticated/errors/$error': typeof AppAuthenticatedErrorsErrorRoute
  '/app/_authenticated/settings/account': typeof AppAuthenticatedSettingsAccountRoute
  '/app/_authenticated/settings/appearance': typeof AppAuthenticatedSettingsAppearanceRoute
  '/app/_authenticated/settings/display': typeof AppAuthenticatedSettingsDisplayRoute
  '/app/_authenticated/settings/notifications': typeof AppAuthenticatedSettingsNotificationsRoute
  '/app/_authenticated/settings/providers': typeof AppAuthenticatedSettingsProvidersRoute
  '/app/_authenticated/ai-chat/': typeof AppAuthenticatedAiChatIndexRoute
  '/app/_authenticated/ai-core/': typeof AppAuthenticatedAiCoreIndexRoute
  '/app/_authenticated/content-studio/': typeof AppAuthenticatedContentStudioIndexRoute
  '/app/_authenticated/crm/': typeof AppAuthenticatedCrmIndexRoute
  '/app/_authenticated/finance/': typeof AppAuthenticatedFinanceIndexRoute
  '/app/_authenticated/models/': typeof AppAuthenticatedModelsIndexRoute
  '/app/_authenticated/presentation-engine/': typeof AppAuthenticatedPresentationEngineIndexRoute
  '/app/_authenticated/restaurant/': typeof AppAuthenticatedRestaurantIndexRoute
  '/app/_authenticated/roles/': typeof AppAuthenticatedRolesIndexRoute
  '/app/_authenticated/settings/': typeof AppAuthenticatedSettingsIndexRoute
  '/app/_authenticated/users/': typeof AppAuthenticatedUsersIndexRoute
  '/app/_authenticated/ai-core/brains/$brainId': typeof AppAuthenticatedAiCoreBrainsBrainIdRoute
  '/app/_authenticated/crm/leads/$leadId': typeof AppAuthenticatedCrmLeadsLeadIdRoute
  '/app/_authenticated/ai-core/audit/': typeof AppAuthenticatedAiCoreAuditIndexRoute
  '/app/_authenticated/ai-core/brains/': typeof AppAuthenticatedAiCoreBrainsIndexRoute
  '/app/_authenticated/ai-core/capabilities/': typeof AppAuthenticatedAiCoreCapabilitiesIndexRoute
  '/app/_authenticated/ai-core/costs/': typeof AppAuthenticatedAiCoreCostsIndexRoute
  '/app/_authenticated/ai-core/health/': typeof AppAuthenticatedAiCoreHealthIndexRoute
  '/app/_authenticated/ai-core/models/': typeof AppAuthenticatedAiCoreModelsIndexRoute
  '/app/_authenticated/ai-core/playground/': typeof AppAuthenticatedAiCorePlaygroundIndexRoute
  '/app/_authenticated/ai-core/providers/': typeof AppAuthenticatedAiCoreProvidersIndexRoute
  '/app/_authenticated/ai-core/usage/': typeof AppAuthenticatedAiCoreUsageIndexRoute
  '/app/_authenticated/automation/audit-logs/': typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  '/app/_authenticated/automation/connections/': typeof AppAuthenticatedAutomationConnectionsIndexRoute
  '/app/_authenticated/automation/health/': typeof AppAuthenticatedAutomationHealthIndexRoute
  '/app/_authenticated/automation/mcp-servers/': typeof AppAuthenticatedAutomationMcpServersIndexRoute
  '/app/_authenticated/automation/providers/': typeof AppAuthenticatedAutomationProvidersIndexRoute
  '/app/_authenticated/crm/leads/': typeof AppAuthenticatedCrmLeadsIndexRoute
  '/app/_authenticated/finance/expenses/': typeof AppAuthenticatedFinanceExpensesIndexRoute
  '/app/_authenticated/restaurant/branches/': typeof AppAuthenticatedRestaurantBranchesIndexRoute
  '/app/_authenticated/restaurant/ingredient-categories/': typeof AppAuthenticatedRestaurantIngredientCategoriesIndexRoute
  '/app/_authenticated/restaurant/ingredients/': typeof AppAuthenticatedRestaurantIngredientsIndexRoute
  '/app/_authenticated/restaurant/menu-categories/': typeof AppAuthenticatedRestaurantMenuCategoriesIndexRoute
  '/app/_authenticated/restaurant/menu-items/': typeof AppAuthenticatedRestaurantMenuItemsIndexRoute
  '/app/_authenticated/restaurant/recipes/': typeof AppAuthenticatedRestaurantRecipesIndexRoute
  '/app/_authenticated/restaurant/restaurants/': typeof AppAuthenticatedRestaurantRestaurantsIndexRoute
  '/app/_authenticated/restaurant/staff/': typeof AppAuthenticatedRestaurantStaffIndexRoute
  '/app/_authenticated/restaurant/suppliers/': typeof AppAuthenticatedRestaurantSuppliersIndexRoute
  '/app/_authenticated/restaurant/units/': typeof AppAuthenticatedRestaurantUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/contact'
    | '/app'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/app/settings'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/app/'
    | '/app/content-studio/$projectId'
    | '/app/content-studio/dashboard'
    | '/app/content-studio/prompt-library'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/notifications'
    | '/app/settings/providers'
    | '/app/ai-chat/'
    | '/app/ai-core/'
    | '/app/content-studio/'
    | '/app/crm/'
    | '/app/finance/'
    | '/app/models/'
    | '/app/presentation-engine/'
    | '/app/restaurant/'
    | '/app/roles/'
    | '/app/settings/'
    | '/app/users/'
    | '/app/ai-core/brains/$brainId'
    | '/app/crm/leads/$leadId'
    | '/app/ai-core/audit/'
    | '/app/ai-core/brains/'
    | '/app/ai-core/capabilities/'
    | '/app/ai-core/costs/'
    | '/app/ai-core/health/'
    | '/app/ai-core/models/'
    | '/app/ai-core/playground/'
    | '/app/ai-core/providers/'
    | '/app/ai-core/usage/'
    | '/app/automation/audit-logs/'
    | '/app/automation/connections/'
    | '/app/automation/health/'
    | '/app/automation/mcp-servers/'
    | '/app/automation/providers/'
    | '/app/crm/leads/'
    | '/app/finance/expenses/'
    | '/app/restaurant/branches/'
    | '/app/restaurant/ingredient-categories/'
    | '/app/restaurant/ingredients/'
    | '/app/restaurant/menu-categories/'
    | '/app/restaurant/menu-items/'
    | '/app/restaurant/recipes/'
    | '/app/restaurant/restaurants/'
    | '/app/restaurant/staff/'
    | '/app/restaurant/suppliers/'
    | '/app/restaurant/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clerk'
    | '/contact'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/app'
    | '/app/content-studio/$projectId'
    | '/app/content-studio/dashboard'
    | '/app/content-studio/prompt-library'
    | '/app/errors/$error'
    | '/app/settings/account'
    | '/app/settings/appearance'
    | '/app/settings/display'
    | '/app/settings/notifications'
    | '/app/settings/providers'
    | '/app/ai-chat'
    | '/app/ai-core'
    | '/app/content-studio'
    | '/app/crm'
    | '/app/finance'
    | '/app/models'
    | '/app/presentation-engine'
    | '/app/restaurant'
    | '/app/roles'
    | '/app/settings'
    | '/app/users'
    | '/app/ai-core/brains/$brainId'
    | '/app/crm/leads/$leadId'
    | '/app/ai-core/audit'
    | '/app/ai-core/brains'
    | '/app/ai-core/capabilities'
    | '/app/ai-core/costs'
    | '/app/ai-core/health'
    | '/app/ai-core/models'
    | '/app/ai-core/playground'
    | '/app/ai-core/providers'
    | '/app/ai-core/usage'
    | '/app/automation/audit-logs'
    | '/app/automation/connections'
    | '/app/automation/health'
    | '/app/automation/mcp-servers'
    | '/app/automation/providers'
    | '/app/crm/leads'
    | '/app/finance/expenses'
    | '/app/restaurant/branches'
    | '/app/restaurant/ingredient-categories'
    | '/app/restaurant/ingredients'
    | '/app/restaurant/menu-categories'
    | '/app/restaurant/menu-items'
    | '/app/restaurant/recipes'
    | '/app/restaurant/restaurants'
    | '/app/restaurant/staff'
    | '/app/restaurant/suppliers'
    | '/app/restaurant/units'
  id:
    | '__root__'
    | '/'
    | '/clerk'
    | '/contact'
    | '/app/_authenticated'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/app/_authenticated/settings'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/app/_authenticated/'
    | '/app/_authenticated/content-studio/$projectId'
    | '/app/_authenticated/content-studio/dashboard'
    | '/app/_authenticated/content-studio/prompt-library'
    | '/app/_authenticated/errors/$error'
    | '/app/_authenticated/settings/account'
    | '/app/_authenticated/settings/appearance'
    | '/app/_authenticated/settings/display'
    | '/app/_authenticated/settings/notifications'
    | '/app/_authenticated/settings/providers'
    | '/app/_authenticated/ai-chat/'
    | '/app/_authenticated/ai-core/'
    | '/app/_authenticated/content-studio/'
    | '/app/_authenticated/crm/'
    | '/app/_authenticated/finance/'
    | '/app/_authenticated/models/'
    | '/app/_authenticated/presentation-engine/'
    | '/app/_authenticated/restaurant/'
    | '/app/_authenticated/roles/'
    | '/app/_authenticated/settings/'
    | '/app/_authenticated/users/'
    | '/app/_authenticated/ai-core/brains/$brainId'
    | '/app/_authenticated/crm/leads/$leadId'
    | '/app/_authenticated/ai-core/audit/'
    | '/app/_authenticated/ai-core/brains/'
    | '/app/_authenticated/ai-core/capabilities/'
    | '/app/_authenticated/ai-core/costs/'
    | '/app/_authenticated/ai-core/health/'
    | '/app/_authenticated/ai-core/models/'
    | '/app/_authenticated/ai-core/playground/'
    | '/app/_authenticated/ai-core/providers/'
    | '/app/_authenticated/ai-core/usage/'
    | '/app/_authenticated/automation/audit-logs/'
    | '/app/_authenticated/automation/connections/'
    | '/app/_authenticated/automation/health/'
    | '/app/_authenticated/automation/mcp-servers/'
    | '/app/_authenticated/automation/providers/'
    | '/app/_authenticated/crm/leads/'
    | '/app/_authenticated/finance/expenses/'
    | '/app/_authenticated/restaurant/branches/'
    | '/app/_authenticated/restaurant/ingredient-categories/'
    | '/app/_authenticated/restaurant/ingredients/'
    | '/app/_authenticated/restaurant/menu-categories/'
    | '/app/_authenticated/restaurant/menu-items/'
    | '/app/_authenticated/restaurant/recipes/'
    | '/app/_authenticated/restaurant/restaurants/'
    | '/app/_authenticated/restaurant/staff/'
    | '/app/_authenticated/restaurant/suppliers/'
    | '/app/_authenticated/restaurant/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  ContactRoute: typeof ContactRoute
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings': {
      id: '/app/_authenticated/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/app/_authenticated/ai-chat/': {
      id: '/app/_authenticated/ai-chat/'
      path: '/ai-chat'
      fullPath: '/app/ai-chat/'
      preLoaderRoute: typeof AppAuthenticatedAiChatIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/': {
      id: '/app/_authenticated/ai-core/'
      path: '/ai-core'
      fullPath: '/app/ai-core/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/': {
      id: '/app/_authenticated/content-studio/'
      path: '/content-studio'
      fullPath: '/app/content-studio/'
      preLoaderRoute: typeof AppAuthenticatedContentStudioIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/$projectId': {
      id: '/app/_authenticated/content-studio/$projectId'
      path: '/content-studio/$projectId'
      fullPath: '/app/content-studio/$projectId'
      preLoaderRoute: typeof AppAuthenticatedContentStudioProjectIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/dashboard': {
      id: '/app/_authenticated/content-studio/dashboard'
      path: '/content-studio/dashboard'
      fullPath: '/app/content-studio/dashboard'
      preLoaderRoute: typeof AppAuthenticatedContentStudioDashboardRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/content-studio/prompt-library': {
      id: '/app/_authenticated/content-studio/prompt-library'
      path: '/content-studio/prompt-library'
      fullPath: '/app/content-studio/prompt-library'
      preLoaderRoute: typeof AppAuthenticatedContentStudioPromptLibraryRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/crm/': {
      id: '/app/_authenticated/crm/'
      path: '/crm'
      fullPath: '/app/crm/'
      preLoaderRoute: typeof AppAuthenticatedCrmIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/errors/$error': {
      id: '/app/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/app/errors/$error'
      preLoaderRoute: typeof AppAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/finance/': {
      id: '/app/_authenticated/finance/'
      path: '/finance'
      fullPath: '/app/finance/'
      preLoaderRoute: typeof AppAuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/models/': {
      id: '/app/_authenticated/models/'
      path: '/models'
      fullPath: '/app/models/'
      preLoaderRoute: typeof AppAuthenticatedModelsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/presentation-engine/': {
      id: '/app/_authenticated/presentation-engine/'
      path: '/presentation-engine'
      fullPath: '/app/presentation-engine/'
      preLoaderRoute: typeof AppAuthenticatedPresentationEngineIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/': {
      id: '/app/_authenticated/restaurant/'
      path: '/restaurant'
      fullPath: '/app/restaurant/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/roles/': {
      id: '/app/_authenticated/roles/'
      path: '/roles'
      fullPath: '/app/roles/'
      preLoaderRoute: typeof AppAuthenticatedRolesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/settings/': {
      id: '/app/_authenticated/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/account': {
      id: '/app/_authenticated/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/appearance': {
      id: '/app/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/display': {
      id: '/app/_authenticated/settings/display'
      path: '/display'
      fullPath: '/app/settings/display'
      preLoaderRoute: typeof AppAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/notifications': {
      id: '/app/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/settings/providers': {
      id: '/app/_authenticated/settings/providers'
      path: '/providers'
      fullPath: '/app/settings/providers'
      preLoaderRoute: typeof AppAuthenticatedSettingsProvidersRouteImport
      parentRoute: typeof AppAuthenticatedSettingsRouteRoute
    }
    '/app/_authenticated/users/': {
      id: '/app/_authenticated/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppAuthenticatedUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/audit/': {
      id: '/app/_authenticated/ai-core/audit/'
      path: '/ai-core/audit'
      fullPath: '/app/ai-core/audit/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreAuditIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/brains/': {
      id: '/app/_authenticated/ai-core/brains/'
      path: '/ai-core/brains'
      fullPath: '/app/ai-core/brains/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreBrainsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/brains/$brainId': {
      id: '/app/_authenticated/ai-core/brains/$brainId'
      path: '/ai-core/brains/$brainId'
      fullPath: '/app/ai-core/brains/$brainId'
      preLoaderRoute: typeof AppAuthenticatedAiCoreBrainsBrainIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/capabilities/': {
      id: '/app/_authenticated/ai-core/capabilities/'
      path: '/ai-core/capabilities'
      fullPath: '/app/ai-core/capabilities/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreCapabilitiesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/costs/': {
      id: '/app/_authenticated/ai-core/costs/'
      path: '/ai-core/costs'
      fullPath: '/app/ai-core/costs/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreCostsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/health/': {
      id: '/app/_authenticated/ai-core/health/'
      path: '/ai-core/health'
      fullPath: '/app/ai-core/health/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreHealthIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/models/': {
      id: '/app/_authenticated/ai-core/models/'
      path: '/ai-core/models'
      fullPath: '/app/ai-core/models/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreModelsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/playground/': {
      id: '/app/_authenticated/ai-core/playground/'
      path: '/ai-core/playground'
      fullPath: '/app/ai-core/playground/'
      preLoaderRoute: typeof AppAuthenticatedAiCorePlaygroundIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/providers/': {
      id: '/app/_authenticated/ai-core/providers/'
      path: '/ai-core/providers'
      fullPath: '/app/ai-core/providers/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreProvidersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/ai-core/usage/': {
      id: '/app/_authenticated/ai-core/usage/'
      path: '/ai-core/usage'
      fullPath: '/app/ai-core/usage/'
      preLoaderRoute: typeof AppAuthenticatedAiCoreUsageIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/audit-logs/': {
      id: '/app/_authenticated/automation/audit-logs/'
      path: '/automation/audit-logs'
      fullPath: '/app/automation/audit-logs/'
      preLoaderRoute: typeof AppAuthenticatedAutomationAuditLogsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/connections/': {
      id: '/app/_authenticated/automation/connections/'
      path: '/automation/connections'
      fullPath: '/app/automation/connections/'
      preLoaderRoute: typeof AppAuthenticatedAutomationConnectionsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/health/': {
      id: '/app/_authenticated/automation/health/'
      path: '/automation/health'
      fullPath: '/app/automation/health/'
      preLoaderRoute: typeof AppAuthenticatedAutomationHealthIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/mcp-servers/': {
      id: '/app/_authenticated/automation/mcp-servers/'
      path: '/automation/mcp-servers'
      fullPath: '/app/automation/mcp-servers/'
      preLoaderRoute: typeof AppAuthenticatedAutomationMcpServersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/automation/providers/': {
      id: '/app/_authenticated/automation/providers/'
      path: '/automation/providers'
      fullPath: '/app/automation/providers/'
      preLoaderRoute: typeof AppAuthenticatedAutomationProvidersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/crm/leads/': {
      id: '/app/_authenticated/crm/leads/'
      path: '/crm/leads'
      fullPath: '/app/crm/leads/'
      preLoaderRoute: typeof AppAuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/crm/leads/$leadId': {
      id: '/app/_authenticated/crm/leads/$leadId'
      path: '/crm/leads/$leadId'
      fullPath: '/app/crm/leads/$leadId'
      preLoaderRoute: typeof AppAuthenticatedCrmLeadsLeadIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/finance/expenses/': {
      id: '/app/_authenticated/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/app/finance/expenses/'
      preLoaderRoute: typeof AppAuthenticatedFinanceExpensesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/branches/': {
      id: '/app/_authenticated/restaurant/branches/'
      path: '/restaurant/branches'
      fullPath: '/app/restaurant/branches/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantBranchesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/ingredient-categories/': {
      id: '/app/_authenticated/restaurant/ingredient-categories/'
      path: '/restaurant/ingredient-categories'
      fullPath: '/app/restaurant/ingredient-categories/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantIngredientCategoriesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/ingredients/': {
      id: '/app/_authenticated/restaurant/ingredients/'
      path: '/restaurant/ingredients'
      fullPath: '/app/restaurant/ingredients/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantIngredientsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/menu-categories/': {
      id: '/app/_authenticated/restaurant/menu-categories/'
      path: '/restaurant/menu-categories'
      fullPath: '/app/restaurant/menu-categories/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantMenuCategoriesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/menu-items/': {
      id: '/app/_authenticated/restaurant/menu-items/'
      path: '/restaurant/menu-items'
      fullPath: '/app/restaurant/menu-items/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantMenuItemsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/recipes/': {
      id: '/app/_authenticated/restaurant/recipes/'
      path: '/restaurant/recipes'
      fullPath: '/app/restaurant/recipes/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantRecipesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/restaurants/': {
      id: '/app/_authenticated/restaurant/restaurants/'
      path: '/restaurant/restaurants'
      fullPath: '/app/restaurant/restaurants/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantRestaurantsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/staff/': {
      id: '/app/_authenticated/restaurant/staff/'
      path: '/restaurant/staff'
      fullPath: '/app/restaurant/staff/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantStaffIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/suppliers/': {
      id: '/app/_authenticated/restaurant/suppliers/'
      path: '/restaurant/suppliers'
      fullPath: '/app/restaurant/suppliers/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantSuppliersIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/app/_authenticated/restaurant/units/': {
      id: '/app/_authenticated/restaurant/units/'
      path: '/restaurant/units'
      fullPath: '/app/restaurant/units/'
      preLoaderRoute: typeof AppAuthenticatedRestaurantUnitsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRoute
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRoute,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface AppAuthenticatedSettingsRouteRouteChildren {
  AppAuthenticatedSettingsAccountRoute: typeof AppAuthenticatedSettingsAccountRoute
  AppAuthenticatedSettingsAppearanceRoute: typeof AppAuthenticatedSettingsAppearanceRoute
  AppAuthenticatedSettingsDisplayRoute: typeof AppAuthenticatedSettingsDisplayRoute
  AppAuthenticatedSettingsNotificationsRoute: typeof AppAuthenticatedSettingsNotificationsRoute
  AppAuthenticatedSettingsProvidersRoute: typeof AppAuthenticatedSettingsProvidersRoute
  AppAuthenticatedSettingsIndexRoute: typeof AppAuthenticatedSettingsIndexRoute
}

const AppAuthenticatedSettingsRouteRouteChildren: AppAuthenticatedSettingsRouteRouteChildren =
  {
    AppAuthenticatedSettingsAccountRoute: AppAuthenticatedSettingsAccountRoute,
    AppAuthenticatedSettingsAppearanceRoute:
      AppAuthenticatedSettingsAppearanceRoute,
    AppAuthenticatedSettingsDisplayRoute: AppAuthenticatedSettingsDisplayRoute,
    AppAuthenticatedSettingsNotificationsRoute:
      AppAuthenticatedSettingsNotificationsRoute,
    AppAuthenticatedSettingsProvidersRoute:
      AppAuthenticatedSettingsProvidersRoute,
    AppAuthenticatedSettingsIndexRoute: AppAuthenticatedSettingsIndexRoute,
  }

const AppAuthenticatedSettingsRouteRouteWithChildren =
  AppAuthenticatedSettingsRouteRoute._addFileChildren(
    AppAuthenticatedSettingsRouteRouteChildren,
  )

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedSettingsRouteRoute: typeof AppAuthenticatedSettingsRouteRouteWithChildren
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedContentStudioProjectIdRoute: typeof AppAuthenticatedContentStudioProjectIdRoute
  AppAuthenticatedContentStudioDashboardRoute: typeof AppAuthenticatedContentStudioDashboardRoute
  AppAuthenticatedContentStudioPromptLibraryRoute: typeof AppAuthenticatedContentStudioPromptLibraryRoute
  AppAuthenticatedErrorsErrorRoute: typeof AppAuthenticatedErrorsErrorRoute
  AppAuthenticatedAiChatIndexRoute: typeof AppAuthenticatedAiChatIndexRoute
  AppAuthenticatedAiCoreIndexRoute: typeof AppAuthenticatedAiCoreIndexRoute
  AppAuthenticatedContentStudioIndexRoute: typeof AppAuthenticatedContentStudioIndexRoute
  AppAuthenticatedCrmIndexRoute: typeof AppAuthenticatedCrmIndexRoute
  AppAuthenticatedFinanceIndexRoute: typeof AppAuthenticatedFinanceIndexRoute
  AppAuthenticatedModelsIndexRoute: typeof AppAuthenticatedModelsIndexRoute
  AppAuthenticatedPresentationEngineIndexRoute: typeof AppAuthenticatedPresentationEngineIndexRoute
  AppAuthenticatedRestaurantIndexRoute: typeof AppAuthenticatedRestaurantIndexRoute
  AppAuthenticatedRolesIndexRoute: typeof AppAuthenticatedRolesIndexRoute
  AppAuthenticatedUsersIndexRoute: typeof AppAuthenticatedUsersIndexRoute
  AppAuthenticatedAiCoreBrainsBrainIdRoute: typeof AppAuthenticatedAiCoreBrainsBrainIdRoute
  AppAuthenticatedCrmLeadsLeadIdRoute: typeof AppAuthenticatedCrmLeadsLeadIdRoute
  AppAuthenticatedAiCoreAuditIndexRoute: typeof AppAuthenticatedAiCoreAuditIndexRoute
  AppAuthenticatedAiCoreBrainsIndexRoute: typeof AppAuthenticatedAiCoreBrainsIndexRoute
  AppAuthenticatedAiCoreCapabilitiesIndexRoute: typeof AppAuthenticatedAiCoreCapabilitiesIndexRoute
  AppAuthenticatedAiCoreCostsIndexRoute: typeof AppAuthenticatedAiCoreCostsIndexRoute
  AppAuthenticatedAiCoreHealthIndexRoute: typeof AppAuthenticatedAiCoreHealthIndexRoute
  AppAuthenticatedAiCoreModelsIndexRoute: typeof AppAuthenticatedAiCoreModelsIndexRoute
  AppAuthenticatedAiCorePlaygroundIndexRoute: typeof AppAuthenticatedAiCorePlaygroundIndexRoute
  AppAuthenticatedAiCoreProvidersIndexRoute: typeof AppAuthenticatedAiCoreProvidersIndexRoute
  AppAuthenticatedAiCoreUsageIndexRoute: typeof AppAuthenticatedAiCoreUsageIndexRoute
  AppAuthenticatedAutomationAuditLogsIndexRoute: typeof AppAuthenticatedAutomationAuditLogsIndexRoute
  AppAuthenticatedAutomationConnectionsIndexRoute: typeof AppAuthenticatedAutomationConnectionsIndexRoute
  AppAuthenticatedAutomationHealthIndexRoute: typeof AppAuthenticatedAutomationHealthIndexRoute
  AppAuthenticatedAutomationMcpServersIndexRoute: typeof AppAuthenticatedAutomationMcpServersIndexRoute
  AppAuthenticatedAutomationProvidersIndexRoute: typeof AppAuthenticatedAutomationProvidersIndexRoute
  AppAuthenticatedCrmLeadsIndexRoute: typeof AppAuthenticatedCrmLeadsIndexRoute
  AppAuthenticatedFinanceExpensesIndexRoute: typeof AppAuthenticatedFinanceExpensesIndexRoute
  AppAuthenticatedRestaurantBranchesIndexRoute: typeof AppAuthenticatedRestaurantBranchesIndexRoute
  AppAuthenticatedRestaurantIngredientCategoriesIndexRoute: typeof AppAuthenticatedRestaurantIngredientCategoriesIndexRoute
  AppAuthenticatedRestaurantIngredientsIndexRoute: typeof AppAuthenticatedRestaurantIngredientsIndexRoute
  AppAuthenticatedRestaurantMenuCategoriesIndexRoute: typeof AppAuthenticatedRestaurantMenuCategoriesIndexRoute
  AppAuthenticatedRestaurantMenuItemsIndexRoute: typeof AppAuthenticatedRestaurantMenuItemsIndexRoute
  AppAuthenticatedRestaurantRecipesIndexRoute: typeof AppAuthenticatedRestaurantRecipesIndexRoute
  AppAuthenticatedRestaurantRestaurantsIndexRoute: typeof AppAuthenticatedRestaurantRestaurantsIndexRoute
  AppAuthenticatedRestaurantStaffIndexRoute: typeof AppAuthenticatedRestaurantStaffIndexRoute
  AppAuthenticatedRestaurantSuppliersIndexRoute: typeof AppAuthenticatedRestaurantSuppliersIndexRoute
  AppAuthenticatedRestaurantUnitsIndexRoute: typeof AppAuthenticatedRestaurantUnitsIndexRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedSettingsRouteRoute:
    AppAuthenticatedSettingsRouteRouteWithChildren,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedContentStudioProjectIdRoute:
    AppAuthenticatedContentStudioProjectIdRoute,
  AppAuthenticatedContentStudioDashboardRoute:
    AppAuthenticatedContentStudioDashboardRoute,
  AppAuthenticatedContentStudioPromptLibraryRoute:
    AppAuthenticatedContentStudioPromptLibraryRoute,
  AppAuthenticatedErrorsErrorRoute: AppAuthenticatedErrorsErrorRoute,
  AppAuthenticatedAiChatIndexRoute: AppAuthenticatedAiChatIndexRoute,
  AppAuthenticatedAiCoreIndexRoute: AppAuthenticatedAiCoreIndexRoute,
  AppAuthenticatedContentStudioIndexRoute:
    AppAuthenticatedContentStudioIndexRoute,
  AppAuthenticatedCrmIndexRoute: AppAuthenticatedCrmIndexRoute,
  AppAuthenticatedFinanceIndexRoute: AppAuthenticatedFinanceIndexRoute,
  AppAuthenticatedModelsIndexRoute: AppAuthenticatedModelsIndexRoute,
  AppAuthenticatedPresentationEngineIndexRoute:
    AppAuthenticatedPresentationEngineIndexRoute,
  AppAuthenticatedRestaurantIndexRoute: AppAuthenticatedRestaurantIndexRoute,
  AppAuthenticatedRolesIndexRoute: AppAuthenticatedRolesIndexRoute,
  AppAuthenticatedUsersIndexRoute: AppAuthenticatedUsersIndexRoute,
  AppAuthenticatedAiCoreBrainsBrainIdRoute:
    AppAuthenticatedAiCoreBrainsBrainIdRoute,
  AppAuthenticatedCrmLeadsLeadIdRoute: AppAuthenticatedCrmLeadsLeadIdRoute,
  AppAuthenticatedAiCoreAuditIndexRoute: AppAuthenticatedAiCoreAuditIndexRoute,
  AppAuthenticatedAiCoreBrainsIndexRoute:
    AppAuthenticatedAiCoreBrainsIndexRoute,
  AppAuthenticatedAiCoreCapabilitiesIndexRoute:
    AppAuthenticatedAiCoreCapabilitiesIndexRoute,
  AppAuthenticatedAiCoreCostsIndexRoute: AppAuthenticatedAiCoreCostsIndexRoute,
  AppAuthenticatedAiCoreHealthIndexRoute:
    AppAuthenticatedAiCoreHealthIndexRoute,
  AppAuthenticatedAiCoreModelsIndexRoute:
    AppAuthenticatedAiCoreModelsIndexRoute,
  AppAuthenticatedAiCorePlaygroundIndexRoute:
    AppAuthenticatedAiCorePlaygroundIndexRoute,
  AppAuthenticatedAiCoreProvidersIndexRoute:
    AppAuthenticatedAiCoreProvidersIndexRoute,
  AppAuthenticatedAiCoreUsageIndexRoute: AppAuthenticatedAiCoreUsageIndexRoute,
  AppAuthenticatedAutomationAuditLogsIndexRoute:
    AppAuthenticatedAutomationAuditLogsIndexRoute,
  AppAuthenticatedAutomationConnectionsIndexRoute:
    AppAuthenticatedAutomationConnectionsIndexRoute,
  AppAuthenticatedAutomationHealthIndexRoute:
    AppAuthenticatedAutomationHealthIndexRoute,
  AppAuthenticatedAutomationMcpServersIndexRoute:
    AppAuthenticatedAutomationMcpServersIndexRoute,
  AppAuthenticatedAutomationProvidersIndexRoute:
    AppAuthenticatedAutomationProvidersIndexRoute,
  AppAuthenticatedCrmLeadsIndexRoute: AppAuthenticatedCrmLeadsIndexRoute,
  AppAuthenticatedFinanceExpensesIndexRoute:
    AppAuthenticatedFinanceExpensesIndexRoute,
  AppAuthenticatedRestaurantBranchesIndexRoute:
    AppAuthenticatedRestaurantBranchesIndexRoute,
  AppAuthenticatedRestaurantIngredientCategoriesIndexRoute:
    AppAuthenticatedRestaurantIngredientCategoriesIndexRoute,
  AppAuthenticatedRestaurantIngredientsIndexRoute:
    AppAuthenticatedRestaurantIngredientsIndexRoute,
  AppAuthenticatedRestaurantMenuCategoriesIndexRoute:
    AppAuthenticatedRestaurantMenuCategoriesIndexRoute,
  AppAuthenticatedRestaurantMenuItemsIndexRoute:
    AppAuthenticatedRestaurantMenuItemsIndexRoute,
  AppAuthenticatedRestaurantRecipesIndexRoute:
    AppAuthenticatedRestaurantRecipesIndexRoute,
  AppAuthenticatedRestaurantRestaurantsIndexRoute:
    AppAuthenticatedRestaurantRestaurantsIndexRoute,
  AppAuthenticatedRestaurantStaffIndexRoute:
    AppAuthenticatedRestaurantStaffIndexRoute,
  AppAuthenticatedRestaurantSuppliersIndexRoute:
    AppAuthenticatedRestaurantSuppliersIndexRoute,
  AppAuthenticatedRestaurantUnitsIndexRoute:
    AppAuthenticatedRestaurantUnitsIndexRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  ContactRoute: ContactRoute,
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
